# Generated by Django 4.2.13 on 2024-06-04 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Select an image for this book', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.language'),
        ),
    ]
