# Generated by Django 4.2.13 on 2024-06-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='not-available.jpg', null=True, upload_to=''),
        ),
    ]
